
# Requires docker-compose >= 1.29.0
version: '3.8'

services:
  postgres:
    image: postgres:alpine
    ports: 
      - 25432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: godwoken_nft_bridge
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  nft-bridge-server:
    image: ghcr.io/classicalliu/godwoken-nft-bridge-server:add-bridge-dc96fa5
    init: true
    volumes:
      - ./.env:/nft-bridge-server/packages/bridge/.env
      - ./entrypoint.sh:/var/lib/bridge/entrypoint.sh
    entrypoint: /var/lib/bridge/entrypoint.sh
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
    depends_on:
      postgres:
        condition: service_started
